### ISSUE TITLE
embed clip-interrogator prompt data (artists/flavours/mediums/movements) #feature?

### ISSUE THREAD

**Issue by bartman081523** [MagnusPetersen/EvoGen-Prompt-Evolution#2]
instead of the english dictionary, can you embed these lists?
https://github.com/pharmapsychotic/clip-interrogator/tree/main/data
all items from these lists have embeddings in laion-aestethic, if i understand correctly.

**Comment by MagnusPetersen** [comment]
Thanks for pointing me to that amazing list collection! Had I known that I would not have had to scrape the stuff myself! I will likely add them but there are still a few features I want to add fist.

**Comment by bartman081523** [comment]
No problem. You can get the laion dataset here: https://laion.ai/blog/laion-aesthetics/
I have downloaded the dataset improved_aesthetics_6.5plus (https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6.5plus)
I can extract the text with this python code:
```
import pyarrow.parquet as pq
table2 = pq.read_table("/content/improved_aesthetics_6.5plus.parquet")
table2.to_pandas()
```
but I am not able to sort the text any further. For me, it seems like a gpt2 model that would be trained with these captions would be the way to go. I think a gpt2 completion would be also possible for evolutionary generations, if you have a base prompt, or a generated base prompt, where gpt2 would replace, or add just one word, or a few words, at a certain point in the phrase. And the prompt would be rated by the asthetics model. This is just an idea, only a suggestion. No obligation.
The idea with gpt2 comes from me, because I dont know how to separate the text clouds from the model. 
When I could separate similar words from the dataset, then I could build a few lists like clip-interrogator, where the prompt is generated from. like this: https://twitter.com/clured/status/1565399157606580224/photo/1

**Comment by MagnusPetersen** [comment]
Thanks for pointing me to the improved aesthetics dataset. Having something on a list like this that CLIP knows and is already preselected for aesthetics is a great boon. I will likely replace the English dictionary with words from those prompts or at least add it as an option. 

Another thing I was thinking about is adding Xander Steenbrugge's random prompts (If he is fine with it of course) made from chunks of other prompts and needed a prompt dataset just for that, so I am glad you linked this since I was about to build a scraper for https://lexica.art/! I am glad I don't need to, thanks! 
Link to Xander's tweet: https://twitter.com/xsteenbrugge/status/1566957648678903811

I don't have much experience with training language models but the Idea is a great one! I was thinking about how to make the randomness more directed. I will look into it but likely a bit down the road.

**Comment by bartman081523** [comment]
As I now see, training a gpt2 model with the laion-captions would be a very special way to go. Since the best aesthetic prompts would have to be discovered *again*. 
But in another way, if you only take the best-rated laion-captions, that might be another way to discover good prompts. 
Yes with gpt2, you could turn up the Temperature to 1 and have a fairly random but contextually fitting output. 
I have asked now @sharifshameem, the creator of lexica, to open-source his dump of stable-diffusion prompts to github (without the images). 
Another way would be to dump the whole dream channels from stable-diffusion and build the prompts from that dataset. 
All in all, I am now off to train a gpt2 model with the laion-6.5+ captions. I get back to you when i created a first prompt.
Someone did the gpt2 training already for midjourney prompts here:
https://huggingface.co/succinctly/text2image-prompt-generator

here is how the midjourney dataset was created:
https://www.kaggle.com/datasets/succinctlyai/midjourney-texttoimage
and here is the compation notebook:
https://www.kaggle.com/code/succinctlyai/midjourney-prompt-analysis/notebook

**Comment by bartman081523** [comment]
I had luck with https://github.com/Tyrrrz/DiscordChatExporter, I could just build the cli in Manjaro with this aur https://aur.archlinux.org/packages/discord-chat-exporter-cli
I found my token in developer settings, with method request header https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#i-cant-findcopy-my-token
I am now scraping only the bots "Dreamt in" messages, where the output is structured, from the dream channels , with `discord-chat-exporter-cli export -c [dream-1-id]  -f csv -t [token] --filter "\"Dreamt in\""`
When I'm done, I will upload the csv dumps to github.

**Comment by bartman081523** [comment]
I have problems with stripping the csv from the prompts. 
I dropped every colums except "Content", but now I have to replace with this pattern
in Notepadqq `(.*\!dream \")(.*)(\" -.*)` replace with capture group 2 `\2` yields the raw prompt.
I can drop the columns with pandas, but I have problems with regex replacing in python. 
Could you help me?
I have this:` "Dreamt in `4.84s` for `!dream ""a sketch of a cluttered robot makers shop with stacks of robot parts and old robots by Jean-Baptiste Monge"" -S 127039764`"
and need this: `"a sketch of a cluttered robot makers shop with stacks of robot parts and old robots by Jean-Baptiste Monge"`

**Comment by bartman081523** [comment]
@MagnusPetersen I have now uploaded every message in all dream channels here
https://github.com/bartman081523/stable-diffusion-discord-prompts
I have the raw messages uploaded and the stripped column "Content", where the "!dream" messages were, 

and in the next days I will upload the rest of the dream-31 to dream-50 prompts-only.
Then I will finetune a gpt2 model with all prompts-only files.

@sharifshameem has not answered me since. But I guess, I (everyone) now have the same base dataset as lexica (without the images).
